# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('device_id', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=100)),
                ('patient_age', models.IntegerField()),
                ('patient_medicines', models.CharField(max_length=500)),
            ],
        ),
    ]
