# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient_medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_device_id', models.CharField(max_length=100)),
                ('medicines', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient_data',
            name='patient_medicines',
        ),
    ]
