# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0002_auto_20171028_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_data',
            name='patient_relatives',
            field=models.CharField(default='', max_length=500),
        ),
    ]
