# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requesthandler', '0003_patient_data_patient_relatives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='device_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
